//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Mangement_System.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Students
    {
        public int id { get; set; }

        [Required(ErrorMessage ="Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Required")]
        public string fname { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string email { get; set; }

        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="Mobile Number Should be 11 Digit")]
        public string mobile { get; set; }

        [Required(ErrorMessage = "Required")]
        public string description { get; set; }
    }
}
